idioma : python
Python :
  - " 3.6-dev "   # 3.6 rama de desarrollo
  - " 3.7-dev "   # 3.7 rama de desarrollo
# comando para instalar dependencias
instalar :
  - pip install requests
guión :
- python TestCynthia.py
#hola
